// Auto-generated from scripts/generate-operation-map.js
// Do not edit manually.
import type { HttpMethod } from './types';

export interface OperationMeta {
  method: HttpMethod;
  path: string;
  resource: string;
  pagination: string[];
  description?: string;
}

export const operationMap = {
  v1_ai_generate_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/ai/generate/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI generation view",
  },
  v1_ai_models_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/ai/models/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI models view",
  },
  v1_ai_providers_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/ai/providers/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI providers view",
  },
  v1_ai_quotas_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/ai/quotas/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI quota view",
  },
  v1_ai_usage_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/ai/usage/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI usage view",
  },
  v2_ai_generate_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/ai/generate/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI generation view",
  },
  v2_ai_models_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/ai/models/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI models view",
  },
  v2_ai_providers_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/ai/providers/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI providers view",
  },
  v2_ai_quotas_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/ai/quotas/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI quota view",
  },
  v2_ai_usage_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/ai/usage/',
    resource: 'Ai',
    pagination: [],
    description: "Placeholder AI usage view",
  },
  v1_analytics_ab_tests_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/analytics/ab-tests/',
    resource: 'Analytics',
    pagination: [],
    description: "Return A/B test results",
  },
  v1_analytics_dashboard_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/analytics/dashboard/',
    resource: 'Analytics',
    pagination: [],
    description: "Return dashboard analytics",
  },
  v1_analytics_recommendations_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/analytics/recommendations/',
    resource: 'Analytics',
    pagination: [],
    description: "Return personalized recommendations",
  },
  v1_analytics_template_analytics_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/analytics/template-analytics/',
    resource: 'Analytics',
    pagination: [],
    description: "Return template analytics",
  },
  v1_analytics_track_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/analytics/track/',
    resource: 'Analytics',
    pagination: [],
    description: "Track an analytics event",
  },
  v1_analytics_user_insights_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/analytics/user-insights/',
    resource: 'Analytics',
    pagination: [],
    description: "Return user insights",
  },
  v2_analytics_ab_tests_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/analytics/ab-tests/',
    resource: 'Analytics',
    pagination: [],
    description: "Return A/B test results",
  },
  v2_analytics_dashboard_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/analytics/dashboard/',
    resource: 'Analytics',
    pagination: [],
    description: "Return dashboard analytics",
  },
  v2_analytics_recommendations_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/analytics/recommendations/',
    resource: 'Analytics',
    pagination: [],
    description: "Return personalized recommendations",
  },
  v2_analytics_template_analytics_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/analytics/template-analytics/',
    resource: 'Analytics',
    pagination: [],
    description: "Return template analytics",
  },
  v2_analytics_track_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/analytics/track/',
    resource: 'Analytics',
    pagination: [],
    description: "Track an analytics event",
  },
  v2_analytics_user_insights_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/analytics/user-insights/',
    resource: 'Analytics',
    pagination: [],
    description: "Return user insights",
  },
  v1_auth_auth_check_email_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/auth/auth/check-email/',
    resource: 'Auth',
    pagination: [],
    description: "Check if email is available for registration\r\n\r\nQuery params:\r\n- email: The email to check\r\n\r\nReturns:\r\n- available: Boolean indicating if email is available",
  },
  v1_auth_change_password_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/auth/change-password/',
    resource: 'Auth',
    pagination: [],
    description: "Handle password change",
  },
  v1_auth_check_username_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/auth/check-username/',
    resource: 'Auth',
    pagination: [],
    description: "Check if username is available for registration\r\n\r\nQuery params:\r\n- username: The username to check\r\n\r\nReturns:\r\n- available: Boolean indicating if username is available",
  },
  v1_auth_login_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/auth/login/',
    resource: 'Auth',
    pagination: [],
    description: "Handle user login",
  },
  v1_auth_logout_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/auth/logout/',
    resource: 'Auth',
    pagination: [],
    description: "Logout user endpoint",
  },
  v1_auth_profile_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/auth/profile/',
    resource: 'Auth',
    pagination: [],
    description: "User profile view for retrieving and updating profile",
  },
  v1_auth_profile_partial_update: {
    method: 'PATCH' as HttpMethod,
    path: '/api/v1/auth/profile/',
    resource: 'Auth',
    pagination: [],
    description: "User profile view for retrieving and updating profile",
  },
  v1_auth_profile_update: {
    method: 'PUT' as HttpMethod,
    path: '/api/v1/auth/profile/',
    resource: 'Auth',
    pagination: [],
    description: "User profile view for retrieving and updating profile",
  },
  v1_auth_profile_update_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/auth/profile/update/',
    resource: 'Auth',
    pagination: [],
    description: "Update user profile endpoint",
  },
  v1_auth_profile_update_partial_update: {
    method: 'PATCH' as HttpMethod,
    path: '/api/v1/auth/profile/update/',
    resource: 'Auth',
    pagination: [],
    description: "Update user profile endpoint",
  },
  v1_auth_profile_update_update: {
    method: 'PUT' as HttpMethod,
    path: '/api/v1/auth/profile/update/',
    resource: 'Auth',
    pagination: [],
    description: "Update user profile endpoint",
  },
  v1_auth_refresh_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/auth/refresh/',
    resource: 'Auth',
    pagination: [],
    description: "Takes a refresh type JSON web token and returns an access type JSON web\r\ntoken if the refresh token is valid.",
  },
  v1_auth_register_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/auth/register/',
    resource: 'Auth',
    pagination: [],
    description: "User registration endpoint\r\n\r\nCreates new user account and returns JWT tokens",
  },
  v1_auth_stats_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/auth/stats/',
    resource: 'Auth',
    pagination: [],
    description: "Get user statistics and gamification data",
  },
  v2_auth_auth_check_email_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/auth/auth/check-email/',
    resource: 'Auth',
    pagination: [],
    description: "Check if email is available for registration\r\n\r\nQuery params:\r\n- email: The email to check\r\n\r\nReturns:\r\n- available: Boolean indicating if email is available",
  },
  v2_auth_change_password_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/auth/change-password/',
    resource: 'Auth',
    pagination: [],
    description: "Handle password change",
  },
  v2_auth_check_username_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/auth/check-username/',
    resource: 'Auth',
    pagination: [],
    description: "Check if username is available for registration\r\n\r\nQuery params:\r\n- username: The username to check\r\n\r\nReturns:\r\n- available: Boolean indicating if username is available",
  },
  v2_auth_login_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/auth/login/',
    resource: 'Auth',
    pagination: [],
    description: "Handle user login",
  },
  v2_auth_logout_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/auth/logout/',
    resource: 'Auth',
    pagination: [],
    description: "Logout user endpoint",
  },
  v2_auth_profile_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/auth/profile/',
    resource: 'Auth',
    pagination: [],
    description: "User profile view for retrieving and updating profile",
  },
  v2_auth_profile_partial_update: {
    method: 'PATCH' as HttpMethod,
    path: '/api/v2/auth/profile/',
    resource: 'Auth',
    pagination: [],
    description: "User profile view for retrieving and updating profile",
  },
  v2_auth_profile_update: {
    method: 'PUT' as HttpMethod,
    path: '/api/v2/auth/profile/',
    resource: 'Auth',
    pagination: [],
    description: "User profile view for retrieving and updating profile",
  },
  v2_auth_profile_update_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/auth/profile/update/',
    resource: 'Auth',
    pagination: [],
    description: "Update user profile endpoint",
  },
  v2_auth_profile_update_partial_update: {
    method: 'PATCH' as HttpMethod,
    path: '/api/v2/auth/profile/update/',
    resource: 'Auth',
    pagination: [],
    description: "Update user profile endpoint",
  },
  v2_auth_profile_update_update: {
    method: 'PUT' as HttpMethod,
    path: '/api/v2/auth/profile/update/',
    resource: 'Auth',
    pagination: [],
    description: "Update user profile endpoint",
  },
  v2_auth_refresh_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/auth/refresh/',
    resource: 'Auth',
    pagination: [],
    description: "Takes a refresh type JSON web token and returns an access type JSON web\r\ntoken if the refresh token is valid.",
  },
  v2_auth_register_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/auth/register/',
    resource: 'Auth',
    pagination: [],
    description: "User registration endpoint\r\n\r\nCreates new user account and returns JWT tokens",
  },
  v2_auth_stats_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/auth/stats/',
    resource: 'Auth',
    pagination: [],
    description: "Get user statistics and gamification data",
  },
  v1_billing_checkout_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/billing/checkout/',
    resource: 'Billing',
    pagination: [],
    description: "Create a Stripe checkout session",
  },
  v1_billing_me_entitlements_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/billing/me/entitlements/',
    resource: 'Billing',
    pagination: [],
    description: "Get user's entitlements based on their subscription",
  },
  v1_billing_me_subscription_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/billing/me/subscription/',
    resource: 'Billing',
    pagination: [],
    description: "Get user's current subscription",
  },
  v1_billing_me_usage_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/billing/me/usage/',
    resource: 'Billing',
    pagination: [],
    description: "Get user's usage statistics",
  },
  v1_billing_plans_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/billing/plans/',
    resource: 'Billing',
    pagination: [],
    description: "List all available billing plans",
  },
  v1_billing_plans_retrieve_2: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/billing/plans/{id}/',
    resource: 'Billing',
    pagination: [],
    description: "Get details of a specific billing plan",
  },
  v1_billing_portal_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/billing/portal/',
    resource: 'Billing',
    pagination: [],
    description: "Create a Stripe customer portal session",
  },
  v1_billing_webhooks_stripe_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/billing/webhooks/stripe/',
    resource: 'Billing',
    pagination: [],
    description: "Handle Stripe webhooks",
  },
  v2_billing_checkout_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/billing/checkout/',
    resource: 'Billing',
    pagination: [],
    description: "Create a Stripe checkout session",
  },
  v2_billing_me_entitlements_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/billing/me/entitlements/',
    resource: 'Billing',
    pagination: [],
    description: "Get user's entitlements based on their subscription",
  },
  v2_billing_me_subscription_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/billing/me/subscription/',
    resource: 'Billing',
    pagination: [],
    description: "Get user's current subscription",
  },
  v2_billing_me_usage_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/billing/me/usage/',
    resource: 'Billing',
    pagination: [],
    description: "Get user's usage statistics",
  },
  v2_billing_plans_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/billing/plans/',
    resource: 'Billing',
    pagination: [],
    description: "List all available billing plans",
  },
  v2_billing_plans_retrieve_2: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/billing/plans/{id}/',
    resource: 'Billing',
    pagination: [],
    description: "Get details of a specific billing plan",
  },
  v2_billing_portal_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/billing/portal/',
    resource: 'Billing',
    pagination: [],
    description: "Create a Stripe customer portal session",
  },
  v2_billing_webhooks_stripe_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/billing/webhooks/stripe/',
    resource: 'Billing',
    pagination: [],
    description: "Handle Stripe webhooks",
  },
  v1_core_config_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/core/config/',
    resource: 'Core',
    pagination: [],
    description: "Return app configuration",
  },
  v1_core_health_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/core/health/',
    resource: 'Core',
    pagination: [],
    description: "Return comprehensive health status",
  },
  v1_core_notifications_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/core/notifications/',
    resource: 'Core',
    pagination: [],
    description: "Get user notifications",
  },
  v1_core_notifications_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/core/notifications/',
    resource: 'Core',
    pagination: [],
    description: "Mark notification as read",
  },
  v2_core_config_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/core/config/',
    resource: 'Core',
    pagination: [],
    description: "Return app configuration",
  },
  v2_core_health_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/core/health/',
    resource: 'Core',
    pagination: [],
    description: "Return comprehensive health status",
  },
  v2_core_notifications_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/core/notifications/',
    resource: 'Core',
    pagination: [],
    description: "Get user notifications",
  },
  v2_core_notifications_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/core/notifications/',
    resource: 'Core',
    pagination: [],
    description: "Mark notification as read",
  },
  v1_gamification_achievements_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/gamification/achievements/',
    resource: 'Gamification',
    pagination: [],
    description: "Get all achievements with user progress",
  },
  v1_gamification_badges_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/gamification/badges/',
    resource: 'Gamification',
    pagination: [],
    description: "Get user's badges",
  },
  v1_gamification_daily_challenges_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/gamification/daily-challenges/',
    resource: 'Gamification',
    pagination: [],
    description: "Get today's challenges",
  },
  v1_gamification_leaderboard_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/gamification/leaderboard/',
    resource: 'Gamification',
    pagination: [],
    description: "Get leaderboard data",
  },
  v1_gamification_streak_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/gamification/streak/',
    resource: 'Gamification',
    pagination: [],
    description: "Get user streak data",
  },
  v1_gamification_user_level_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/gamification/user-level/',
    resource: 'Gamification',
    pagination: [],
    description: "Get user level information",
  },
  v2_gamification_achievements_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/gamification/achievements/',
    resource: 'Gamification',
    pagination: [],
    description: "Get all achievements with user progress",
  },
  v2_gamification_badges_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/gamification/badges/',
    resource: 'Gamification',
    pagination: [],
    description: "Get user's badges",
  },
  v2_gamification_daily_challenges_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/gamification/daily-challenges/',
    resource: 'Gamification',
    pagination: [],
    description: "Get today's challenges",
  },
  v2_gamification_leaderboard_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/gamification/leaderboard/',
    resource: 'Gamification',
    pagination: [],
    description: "Get leaderboard data",
  },
  v2_gamification_streak_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/gamification/streak/',
    resource: 'Gamification',
    pagination: [],
    description: "Get user streak data",
  },
  v2_gamification_user_level_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/gamification/user-level/',
    resource: 'Gamification',
    pagination: [],
    description: "Get user level information",
  },
  health_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/health/',
    resource: 'Health',
    pagination: [],
    description: "Return comprehensive health status",
  },
  v1_orchestrator_assess_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/orchestrator/assess/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Assess prompt quality and provide suggestions",
  },
  v1_orchestrator_intent_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/orchestrator/intent/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Detect user intent from prompt",
  },
  v1_orchestrator_render_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/orchestrator/render/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Render a template with provided variables",
  },
  v1_orchestrator_search_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/orchestrator/search/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Search for templates in the library",
  },
  v1_orchestrator_template_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/orchestrator/template/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Get a specific template by ID or name",
  },
  v1_orchestrator_template_retrieve_2: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/orchestrator/template/{template_id}/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Get a specific template by ID or name",
  },
  v2_orchestrator_assess_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/orchestrator/assess/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Assess prompt quality and provide suggestions",
  },
  v2_orchestrator_intent_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/orchestrator/intent/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Detect user intent from prompt",
  },
  v2_orchestrator_render_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/orchestrator/render/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Render a template with provided variables",
  },
  v2_orchestrator_search_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/orchestrator/search/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Search for templates in the library",
  },
  v2_orchestrator_template_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/orchestrator/template/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Get a specific template by ID or name",
  },
  v2_orchestrator_template_retrieve_2: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/orchestrator/template/{template_id}/',
    resource: 'Orchestrator',
    pagination: [],
    description: "Get a specific template by ID or name",
  },
  v1_template_categories_list: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/template-categories/',
    resource: 'Templates',
    pagination: ["ordering","page","search"],
    description: "ViewSet for template categories\r\n\r\nProvides:\r\n- List all categories\r\n- Retrieve single category\r\n- Category statistics",
  },
  v1_template_categories_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/template-categories/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "ViewSet for template categories\r\n\r\nProvides:\r\n- List all categories\r\n- Retrieve single category\r\n- Category statistics",
  },
  v1_template_categories_templates_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/template-categories/{id}/templates/',
    resource: 'Templates',
    pagination: [],
    description: "Get templates in this category",
  },
  v1_templates_list: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/templates/',
    resource: 'Templates',
    pagination: ["ordering","page","search"],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v1_templates_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/templates/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v1_templates_destroy: {
    method: 'DELETE' as HttpMethod,
    path: '/api/v1/templates/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v1_templates_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/templates/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v1_templates_partial_update: {
    method: 'PATCH' as HttpMethod,
    path: '/api/v1/templates/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v1_templates_update: {
    method: 'PUT' as HttpMethod,
    path: '/api/v1/templates/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v1_templates_analytics_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/templates/{id}/analytics/',
    resource: 'Templates',
    pagination: [],
    description: "Get detailed analytics for a template (author only)",
  },
  v1_templates_analyze_with_ai_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/templates/{id}/analyze_with_ai/',
    resource: 'Templates',
    pagination: [],
    description: "Analyze template with AI for optimization suggestions",
  },
  v1_templates_complete_usage_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/templates/{id}/complete_usage/',
    resource: 'Templates',
    pagination: [],
    description: "Complete template usage and award rewards",
  },
  v1_templates_duplicate_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/templates/{id}/duplicate/',
    resource: 'Templates',
    pagination: [],
    description: "Create a copy of an existing template",
  },
  v1_templates_rate_template_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/templates/{id}/rate_template/',
    resource: 'Templates',
    pagination: [],
    description: "Rate and review a template",
  },
  v1_templates_start_usage_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v1/templates/{id}/start_usage/',
    resource: 'Templates',
    pagination: [],
    description: "Start using a template - creates usage tracking record",
  },
  v1_templates_featured_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/templates/featured/',
    resource: 'Templates',
    pagination: [],
    description: "Get featured templates",
  },
  v1_templates_my_templates_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/templates/my_templates/',
    resource: 'Templates',
    pagination: [],
    description: "Get current user's templates",
  },
  v1_templates_search_suggestions_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/templates/search_suggestions/',
    resource: 'Templates',
    pagination: [],
    description: "Get search suggestions based on popular templates and tags",
  },
  v1_templates_trending_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v1/templates/trending/',
    resource: 'Templates',
    pagination: [],
    description: "Get trending templates based on recent activity",
  },
  v2_template_categories_list: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/template-categories/',
    resource: 'Templates',
    pagination: ["ordering","page","search"],
    description: "ViewSet for template categories\r\n\r\nProvides:\r\n- List all categories\r\n- Retrieve single category\r\n- Category statistics",
  },
  v2_template_categories_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/template-categories/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "ViewSet for template categories\r\n\r\nProvides:\r\n- List all categories\r\n- Retrieve single category\r\n- Category statistics",
  },
  v2_template_categories_templates_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/template-categories/{id}/templates/',
    resource: 'Templates',
    pagination: [],
    description: "Get templates in this category",
  },
  v2_templates_list: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/templates/',
    resource: 'Templates',
    pagination: ["ordering","page","search"],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v2_templates_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/templates/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v2_templates_destroy: {
    method: 'DELETE' as HttpMethod,
    path: '/api/v2/templates/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v2_templates_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/templates/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v2_templates_partial_update: {
    method: 'PATCH' as HttpMethod,
    path: '/api/v2/templates/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v2_templates_update: {
    method: 'PUT' as HttpMethod,
    path: '/api/v2/templates/{id}/',
    resource: 'Templates',
    pagination: [],
    description: "Complete CRUD ViewSet for templates\r\n\r\nFeatures:\r\n- List, create, retrieve, update, delete templates\r\n- Advanced filtering and search\r\n- Custom actions for usage tracking\r\n- AI integration\r\n- Analytics and ratings",
  },
  v2_templates_analytics_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/templates/{id}/analytics/',
    resource: 'Templates',
    pagination: [],
    description: "Get detailed analytics for a template (author only)",
  },
  v2_templates_analyze_with_ai_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/templates/{id}/analyze_with_ai/',
    resource: 'Templates',
    pagination: [],
    description: "Analyze template with AI for optimization suggestions",
  },
  v2_templates_complete_usage_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/templates/{id}/complete_usage/',
    resource: 'Templates',
    pagination: [],
    description: "Complete template usage and award rewards",
  },
  v2_templates_duplicate_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/templates/{id}/duplicate/',
    resource: 'Templates',
    pagination: [],
    description: "Create a copy of an existing template",
  },
  v2_templates_rate_template_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/templates/{id}/rate_template/',
    resource: 'Templates',
    pagination: [],
    description: "Rate and review a template",
  },
  v2_templates_start_usage_create: {
    method: 'POST' as HttpMethod,
    path: '/api/v2/templates/{id}/start_usage/',
    resource: 'Templates',
    pagination: [],
    description: "Start using a template - creates usage tracking record",
  },
  v2_templates_featured_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/templates/featured/',
    resource: 'Templates',
    pagination: [],
    description: "Get featured templates",
  },
  v2_templates_my_templates_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/templates/my_templates/',
    resource: 'Templates',
    pagination: [],
    description: "Get current user's templates",
  },
  v2_templates_search_suggestions_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/templates/search_suggestions/',
    resource: 'Templates',
    pagination: [],
    description: "Get search suggestions based on popular templates and tags",
  },
  v2_templates_trending_retrieve: {
    method: 'GET' as HttpMethod,
    path: '/api/v2/templates/trending/',
    resource: 'Templates',
    pagination: [],
    description: "Get trending templates based on recent activity",
  },
} as const satisfies Record<string, OperationMeta>;

export type OperationId = keyof typeof operationMap;