import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  resolvePluginsRelativeTo: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // TypeScript/TSX rules
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unsafe-function-type": "error",
      "@typescript-eslint/no-empty-object-type": "error",
      "@typescript-eslint/no-require-imports": "error",
      "prefer-const": "error",
      "no-var": "error",
      "react/jsx-key": "error",
      "react/no-unescaped-entities": "off",
      "@next/next/no-img-element": "warn",
    },
  },
  // Tests: relax a few React lint rules
  {
    files: ["**/*.test.{ts,tsx}", "**/__tests__/**/*.{ts,tsx}"] ,
    rules: {
      "react/display-name": "off",
      "@typescript-eslint/no-explicit-any": "off",
      // Allow harmless unused variables in tests
      "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }],
    },
  },
  // JavaScript rules (loosen TS-specific checks for Node scripts/tests)
  {
    files: ["**/*.{js,jsx}"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-var-requires": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  // Pages: tolerate unused imports/vars during UI assembly (fix incrementally)
  {
    files: ["src/app/**/page.tsx"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // Per-file tweaks and ignores
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "dist/**",
      "build/**",
      "coverage/**",
      "*.config.js",
      "*.config.mjs",
      "*.config.ts",
      ".env*",
      // Generated by Next.js
      "next-env.d.ts",
      // Ignore known WIP/legacy pages with parse errors until fixed
      "src/app/**/page-old.tsx",
      "src/app/**/page.old.tsx",
      "src/app/**/page-backup.tsx",
      "src/app/**/page-news.tsx",
      // Ignore legacy template implementations with JSX parse issues
      "src/components/templates/**",
      // Ignore specific debug/health components with JSX issues
      "src/components/ProductionHealthCheck.tsx",
      "src/components/ConnectionStatus.tsx",
    ],
  },
];

export default eslintConfig;
